# Generated by Django 6.0 on 2026-07-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='promotion',
            new_name='promotions__start_d_283aa1_idx',
            old_name='promotions_p_start_d_idx',
        ),
        migrations.RenameIndex(
            model_name='promotion',
            new_name='promotions__is_acti_fc6f30_idx',
            old_name='promotions_p_is_act_idx',
        ),
        migrations.RenameIndex(
            model_name='promotionlog',
            new_name='promotions__promoti_889145_idx',
            old_name='promotions_p_promot_d3ad4a_idx',
        ),
    ]
