# Generated by Django 6.0 on 2025-12-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="L'excellence depuis 1985", max_length=200)),
                ('paragraph1', models.TextField(verbose_name='Paragraphe 1')),
                ('paragraph2', models.TextField(blank=True, verbose_name='Paragraphe 2')),
                ('image', models.ImageField(upload_to='about/')),
            ],
            options={
                'verbose_name': 'Section A Propos',
                'verbose_name_plural': 'Section A Propos',
            },
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Ex: 38+', max_length=50)),
                ('label', models.CharField(help_text="Ex: Années d'expérience", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Statistique A Propos',
                'verbose_name_plural': 'Statistiques A Propos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='hero_cards/')),
                ('link_text', models.CharField(default='Explorer', max_length=50)),
                ('link_url', models.CharField(default='#', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Carte Hero',
                'verbose_name_plural': 'Cartes Hero',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="L'élégance redéfinie", max_length=200)),
                ('subtitle', models.TextField(default='Découvrez notre nouvelle collection de bijoux artisanaux, conçus pour sublimer chaque instant de votre vie.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('button_text', models.CharField(default='Découvrir la collection', max_length=50)),
                ('button_link', models.CharField(default='#catalogue', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Section Hero (Bannière)',
                'verbose_name_plural': 'Sections Hero',
            },
        ),
        migrations.AlterModelOptions(
            name='storesettings',
            options={'verbose_name': 'Configuration Site', 'verbose_name_plural': 'Configuration Site'},
        ),
    ]
