# Generated by Django 6.0 on 2025-12-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_aboutsection_aboutstat_herocard_herosection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter_title', models.CharField(default='Restez informé', max_length=100)),
                ('newsletter_text', models.TextField(default='Inscrivez-vous pour recevoir nos nouveautés et offres exclusives.')),
                ('company_description', models.TextField(default="L'excellence artisanale depuis 2024.")),
                ('address', models.TextField(default='Route des huileries\nN° 160, Av. Usoke, C/Lingwala')),
                ('phone', models.CharField(default='+243 97 67 977 48', max_length=50)),
                ('email', models.EmailField(default='info@mkaribu.com', max_length=254)),
                ('copyright_text', models.CharField(default='© 2024 Mkaribu Store. Tous droits réservés.', max_length=200)),
            ],
            options={
                'verbose_name': 'Configuration Footer',
                'verbose_name_plural': 'Configuration Footer',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('help', 'Aide'), ('legal', 'Légal'), ('boutique', 'Boutique (Optionnel)')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='URL absolute or Django named URL', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Lien Footer',
                'verbose_name_plural': 'Liens Footer',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Facebook', max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text="Bootstrap icon class e.g. 'bi bi-facebook'", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Lien Social',
                'verbose_name_plural': 'Liens Sociaux',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrustSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_content', models.TextField(help_text='Raw SVG content for the icon')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Signal de Confiance',
                'verbose_name_plural': 'Signaux de Confiance',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='universes/')),
                ('identifier', models.CharField(help_text="Internal ID for JS filtering (e.g., 'BIJOUX SIMPLES'). Do not change unless you update the code.", max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Univers (Navigateur)',
                'verbose_name_plural': 'Univers (Navigateur)',
                'ordering': ['order'],
            },
        ),
    ]
