# Generated by Django 5.0.6 on 2025-12-19 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_category'),
        ('store', '0004_footerconfig_footerlink_sociallink_trustsignal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional. If empty, uses the Category name.', max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text="e.g. 'Élégance intemporelle'", max_length=100)),
                ('image', models.ImageField(help_text='Image spécifique pour la carte collection (haute qualité)', upload_to='collections/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='products.category')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['order'],
            },
        ),
    ]
