# Generated by Django 6.0 on 2025-12-29 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_category'),
        ('store', '0005_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universes', to='products.category'),
        ),
    ]
