# Generated by Django 6.0 on 2026-01-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_universe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='customization_data',
            field=models.JSONField(blank=True, default=dict, help_text="Structure: {'choices': {'zone_id': value}}", null=True, verbose_name='Données de personnalisation'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='cart_previews/', verbose_name='Aperçu personnalisation'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price_at_addition',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix Base + Options au moment de l'ajout", max_digits=10, null=True, verbose_name='Prix unitaire figé'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='production_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Instructions de production'),
        ),
        migrations.AddField(
            model_name='weborderitem',
            name='customization_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Données personnalisation'),
        ),
        migrations.AddField(
            model_name='weborderitem',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='order_previews/', verbose_name='Aperçu personnalisation'),
        ),
        migrations.AddField(
            model_name='weborderitem',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nom produit (snapshot)'),
        ),
        migrations.AddField(
            model_name='weborderitem',
            name='production_data',
            field=models.JSONField(blank=True, default=dict, help_text='Instructions de création/gravure/impression', null=True, verbose_name='Instructions atelier'),
        ),
        migrations.AlterField(
            model_name='weborderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (snapshot)'),
        ),
    ]
