# Generated by Django 6.0 on 2026-02-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cartitem_customization_data_cartitem_preview_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weborderitem',
            name='client_image',
            field=models.ImageField(blank=True, null=True, upload_to='order_client_photos/', verbose_name='Photo client originale'),
        ),
    ]
