# Generated by Django 6.0 on 2026-02-19 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_weborderitem_client_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='weborder',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'En attente de paiement'), ('awaiting_verification', 'En attente de vérification'), ('paid', 'Payé'), ('cancelled', 'Annulé'), ('shipped', 'Expédié'), ('delivered', 'Livré')], default='pending_payment', max_length=30),
        ),
        migrations.AlterField(
            model_name='weborder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='ManualPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('m-pesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('orange', 'Orange Money'), ('virement', 'Virement Bancaire'), ('cash', 'Cash / Espèces')], max_length=20)),
                ('transaction_ref', models.CharField(max_length=100, verbose_name='Référence Transaction')),
                ('proof_file', models.FileField(upload_to='payment_proofs/', verbose_name='Preuve de paiement')),
                ('status', models.CharField(choices=[('submitted', 'Soumis'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='submitted', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Motif de rejet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_payment', to='store.weborder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement Manuel',
                'verbose_name_plural': 'Paiements Manuels',
            },
        ),
    ]
