# Generated by Django 6.0 on 2026-03-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_adminnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la zone')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tarif de livraison')),
                ('is_active', models.BooleanField(default=True, verbose_name='Zone active ?')),
            ],
            options={
                'verbose_name': 'Zone de Livraison',
                'verbose_name_plural': 'Zones de Livraison',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='weborder',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Frais de livraison appliqués'),
        ),
        migrations.AddField(
            model_name='weborder',
            name='delivery_zone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zone de livraison sélectionnée'),
        ),
    ]
