# Generated by Django 6.0 on 2026-03-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_deliveryzone_weborder_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualpayment',
            name='payment_method',
            field=models.CharField(choices=[('m-pesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('orange', 'Orange Money'), ('virement', 'Virement Bancaire'), ('cash', 'Paiement en Boutique'), ('delivery-cash', 'Paiement à la Livraison')], max_length=20),
        ),
    ]
