# Generated by Django 6.0 on 2026-04-03 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_manualpayment_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weborder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='manualpayment',
            index=models.Index(fields=['status', 'created_at'], name='store_manua_status_e6852b_idx'),
        ),
        migrations.AddIndex(
            model_name='manualpayment',
            index=models.Index(fields=['user', 'created_at'], name='store_manua_user_id_f4126d_idx'),
        ),
        migrations.AddIndex(
            model_name='weborder',
            index=models.Index(fields=['status', 'created_at'], name='store_webor_status_c83239_idx'),
        ),
        migrations.AddIndex(
            model_name='weborder',
            index=models.Index(fields=['user', 'created_at'], name='store_webor_user_id_2a131f_idx'),
        ),
    ]
