# Generated by Django 6.0 on 2026-04-03 17:48

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
from django.utils.crypto import get_random_string


def populate_weborder_identifiers(apps, schema_editor):
    WebOrder = apps.get_model('store', 'WebOrder')

    for order in WebOrder.objects.all().order_by('created_at', 'id'):
        update_fields = []

        if not order.payment_method:
            order.payment_method = 'm-pesa'
            update_fields.append('payment_method')

        if not order.order_number:
            created_at = timezone.localtime(order.created_at or timezone.now())
            order.order_number = f"CMD-{created_at.strftime('%Y%m%d')}-{order.pk:06d}"
            update_fields.append('order_number')

        if order.payment_method == 'delivery-cash' and not order.delivery_confirmation_code:
            order.delivery_confirmation_code = get_random_string(
                8,
                allowed_chars='23456789ABCDEFGHJKLMNPQRSTUVWXYZ',
            )
            update_fields.append('delivery_confirmation_code')

        if update_fields:
            order.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_weborder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weborder',
            name='delivery_confirmation_code',
            field=models.CharField(blank=True, max_length=12, verbose_name='Code de remise'),
        ),
        migrations.AddField(
            model_name='weborder',
            name='order_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Reference commande'),
        ),
        migrations.AddField(
            model_name='weborder',
            name='payment_method',
            field=models.CharField(choices=[('m-pesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('orange', 'Orange Money'), ('virement', 'Virement Bancaire'), ('cash', 'Paiement en Boutique'), ('delivery-cash', 'Paiement a la Livraison')], default='m-pesa', max_length=20),
        ),
        migrations.RunPython(populate_weborder_identifiers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='weborder',
            name='order_number',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Reference commande'),
        ),
    ]
