# Generated by Django 6.0 on 2026-04-03 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_weborder_delivery_confirmation_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePickupVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Numéro du bon')),
                ('pickup_code', models.CharField(blank=True, max_length=8, verbose_name='Code de récupération')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='vouchers_qr/', verbose_name='Code QR')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('picked_up', 'Retiré'), ('cancelled', 'Annulé')], default='active', max_length=20)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de retrait')),
                ('picked_up_by', models.CharField(blank=True, max_length=255, verbose_name='Retiré par')),
                ('valid_until', models.DateTimeField(verbose_name="Valide jusqu'au")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_voucher', to='store.weborder')),
            ],
            options={
                'verbose_name': 'Bon de retrait',
                'verbose_name_plural': 'Bons de retrait',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='store_store_status_f14f8b_idx'), models.Index(fields=['order'], name='store_store_order_i_c38b48_idx')],
            },
        ),
    ]
