# Generated by Django 6.0 on 2026-04-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_storepickupvoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='weborder',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'Retrait en boutique'), ('delivery', 'Livraison à domicile')], default='delivery', max_length=20, verbose_name='Type de livraison'),
        ),
    ]
