# Generated by Django 6.0 on 2026-06-26 23:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_shop_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('commune', models.CharField(max_length=80)),
                ('address', models.TextField(blank=True)),
                ('coverage_communes', models.JSONField(blank=True, default=list)),
                ('manager_phone', models.CharField(blank=True, max_length=50)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hub PEMBENY',
                'verbose_name_plural': 'Hubs PEMBENY',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Nom')),
                ('category', models.CharField(choices=[('beverages', 'Boissons'), ('food', 'Alimentaire'), ('hygiene', 'Hygiene'), ('flour', 'Farine et cereales'), ('snacks', 'Snacks'), ('other', 'Autre')], default='other', max_length=30)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='supply/suppliers/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fournisseur PEMBENY',
                'verbose_name_plural': 'Fournisseurs PEMBENY',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MerchantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(blank=True, max_length=80)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('credit_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_credit_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_accounts', to='supply.hub')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_account', to='accounts.shop')),
            ],
            options={
                'verbose_name': 'Compte boutique PEMBENY',
                'verbose_name_plural': 'Comptes boutiques PEMBENY',
            },
        ),
        migrations.CreateModel(
            name='ProcurementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('merchant_name', models.CharField(max_length=180)),
                ('commune', models.CharField(max_length=80)),
                ('delivery_address', models.TextField()),
                ('contact_phone', models.CharField(max_length=50)),
                ('payment_method', models.CharField(choices=[('m-pesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('orange', 'Orange Money'), ('bank', 'Virement bancaire'), ('credit', 'Credit marchandises'), ('delivery-cash', 'Paiement a la livraison')], default='m-pesa', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pending_payment', 'Paiement en attente'), ('awaiting_preparation', 'En attente de preparation'), ('preparing', 'Preparation au hub'), ('ready_for_dispatch', 'Prete pour expedition'), ('out_for_delivery', 'En livraison'), ('delivered', 'Livree'), ('cancelled', 'Annulee')], default='pending_payment', max_length=30)),
                ('delivery_eta', models.DateTimeField(blank=True, null=True)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('escrow_released', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='supply.hub')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_orders', to='accounts.shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande approvisionnement',
                'verbose_name_plural': 'Commandes approvisionnement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderTrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_payment', 'Paiement en attente'), ('awaiting_preparation', 'En attente de preparation'), ('preparing', 'Preparation au hub'), ('ready_for_dispatch', 'Prete pour expedition'), ('out_for_delivery', 'En livraison'), ('delivered', 'Livree'), ('cancelled', 'Annulee')], max_length=30)),
                ('label', models.CharField(max_length=160)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='supply.procurementorder')),
            ],
            options={
                'verbose_name': 'Evenement de suivi',
                'verbose_name_plural': 'Evenements de suivi',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('category', models.CharField(choices=[('beverages', 'Boissons'), ('food', 'Alimentaire'), ('hygiene', 'Hygiene'), ('flour', 'Farine et cereales'), ('snacks', 'Snacks'), ('other', 'Autre')], default='other', max_length=30)),
                ('unit_label', models.CharField(help_text='Ex: caisse 24 bouteilles, carton 40 paquets', max_length=120)),
                ('package_size', models.PositiveIntegerField(default=1)),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], default='USD', max_length=3)),
                ('minimum_order_quantity', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='supply/products/')),
                ('icon_class', models.CharField(default='bi-box-seam', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='supply.supplier')),
            ],
            options={
                'verbose_name': 'Produit approvisionnement',
                'verbose_name_plural': 'Produits approvisionnement',
                'ordering': ['supplier__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=180)),
                ('supplier_name', models.CharField(blank=True, max_length=160)),
                ('unit_label', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supply.procurementorder')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='supply.supplier')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='supply.supplyproduct')),
            ],
            options={
                'verbose_name': 'Ligne approvisionnement',
                'verbose_name_plural': 'Lignes approvisionnement',
            },
        ),
        migrations.CreateModel(
            name='HubInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('reorder_threshold', models.PositiveIntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='supply.hub')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_inventories', to='supply.supplyproduct')),
            ],
            options={
                'verbose_name': 'Stock hub',
                'verbose_name_plural': 'Stocks hubs',
                'ordering': ['hub__name', 'product__name'],
            },
        ),
        migrations.AddIndex(
            model_name='procurementorder',
            index=models.Index(fields=['status', 'created_at'], name='supply_proc_status_d9b726_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementorder',
            index=models.Index(fields=['shop', 'created_at'], name='supply_proc_shop_id_f1a550_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementorder',
            index=models.Index(fields=['hub', 'status'], name='supply_proc_hub_id_34d548_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyproduct',
            index=models.Index(fields=['category', 'is_active'], name='supply_supp_categor_918b69_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyproduct',
            index=models.Index(fields=['supplier', 'is_active'], name='supply_supp_supplie_cc50d8_idx'),
        ),
        migrations.AddIndex(
            model_name='hubinventory',
            index=models.Index(fields=['hub', 'product'], name='supply_hubi_hub_id_dd7c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='hubinventory',
            index=models.Index(fields=['available_quantity', 'reserved_quantity'], name='supply_hubi_availab_81a603_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hubinventory',
            unique_together={('hub', 'product')},
        ),
    ]
