# Generated by Django 6.0 on 2026-06-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyHomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='bi-box-seam', max_length=60)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('badge', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Carte avantage PEMBENY',
                'verbose_name_plural': 'Cartes avantages PEMBENY',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplyHomepageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Statistique accueil PEMBENY',
                'verbose_name_plural': 'Statistiques accueil PEMBENY',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplyProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('icon_class', models.CharField(default='bi-check-circle', max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Etape processus PEMBENY',
                'verbose_name_plural': 'Etapes processus PEMBENY',
                'ordering': ['order', 'number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplySiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='PEMBENY', max_length=80)),
                ('brand_signature', models.CharField(default='By Dellions Group', max_length=120)),
                ('hero_badge', models.CharField(default='Reseau B2B Kinshasa', max_length=160)),
                ('hero_title', models.CharField(default='Approvisionnez votre boutique depuis les fournisseurs partenaires.', max_length=220)),
                ('hero_subtitle', models.TextField(default='Catalogue centralise, stock par hub, panier rapide, paiement flexible et suivi de livraison vers votre point de vente.')),
                ('primary_cta_text', models.CharField(default='Creer ma boutique', max_length=80)),
                ('primary_cta_url', models.CharField(default='/supply/register/', max_length=200)),
                ('secondary_cta_text', models.CharField(default='Voir le catalogue', max_length=80)),
                ('secondary_cta_url', models.CharField(default='#catalogue', max_length=200)),
                ('network_title', models.CharField(default='Comment PEMBENY organise votre approvisionnement', max_length=160)),
                ('network_subtitle', models.TextField(default='PEMBENY connecte les fournisseurs, les hubs de distribution et les boutiques dans une seule experience.')),
                ('contact_phone', models.CharField(default='(+243) 0829959698', max_length=50)),
                ('footer_text', models.CharField(default='PEMBENY / Dellions Group SARL - Kinshasa', max_length=180)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='supply/site/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration site PEMBENY',
                'verbose_name_plural': 'Configuration site PEMBENY',
            },
        ),
    ]
