# Generated by Django 6.0 on 2026-07-01 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_supplyhomefeature_supplyhomepagestat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantaccount',
            name='business_age',
            field=models.CharField(choices=[('under_3_months', 'Moins de 3 mois'), ('3_to_6_months', '3 a 6 mois'), ('6_to_12_months', '6 a 12 mois'), ('over_12_months', 'Plus de 12 mois')], default='6_to_12_months', max_length=40),
        ),
        migrations.AddField(
            model_name='merchantaccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='merchantaccount',
            name='owner_full_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='merchantaccount',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='merchantaccount',
            name='shop_type',
            field=models.CharField(choices=[('depot_wholesaler', 'Depot / Grossiste'), ('neighborhood_shop', 'Boutique de quartier'), ('brewery_shop', 'Boutique brassicole'), ('pharmacy_drugstore', 'Pharmacie / Drugstore'), ('hardware_store', 'Quincaillerie'), ('other', 'Autre')], default='neighborhood_shop', max_length=40),
        ),
        migrations.AddField(
            model_name='merchantaccount',
            name='storefront_photo',
            field=models.ImageField(blank=True, null=True, upload_to='supply/storefronts/'),
        ),
        migrations.AddField(
            model_name='merchantaccount',
            name='whatsapp_active',
            field=models.BooleanField(default=True),
        ),
    ]
