# Generated by Django 6.0 on 2026-07-02 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0004_supplycategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.CharField(choices=[('beverages', 'Boissons'), ('food', 'Alimentaire'), ('hygiene', 'Hygiene'), ('flour', 'Farine et cereales'), ('snacks', 'Snacks'), ('other', 'Autre')], default='other', max_length=30, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nom du contact'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='supply/suppliers/', verbose_name='Logo du fournisseur'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Nom du fournisseur'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='supplyproduct',
            name='brand',
            field=models.CharField(blank=True, max_length=120, verbose_name='Marque'),
        ),
        migrations.AlterField(
            model_name='supplyproduct',
            name='category',
            field=models.CharField(choices=[('beverages', 'Boissons'), ('food', 'Alimentaire'), ('hygiene', 'Hygiene'), ('flour', 'Farine et cereales'), ('snacks', 'Snacks'), ('other', 'Autre')], default='other', max_length=30, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='supplyproduct',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], default='USD', max_length=3, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='supplyproduct',
            name='icon_class',
            field=models.CharField(default='bi-box-seam', max_length=60, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='supplyproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='supply/products/', verbose_name='Image du produit'),
        ),
        migrations.AlterField(
            model_name='supplyproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='supplyproduct',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Mis en avant'),
        ),
        migrations.AlterField(
            model_name='supplyproduct',
            name='minimum_order_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité minimum de commande'),
        ),
        migrations.AlterField(
            model_name='supplyproduct',
            name='name',
            field=models.CharField(max_length=180, verbose_name='Nom du produit'),
        ),
        migrations.AlterField(
            model_name='supplyproduct',
            name='package_size',
            field=models.PositiveIntegerField(default=1, verbose_name='Taille du package'),
        ),
        migrations.AlterField(
            model_name='supplyproduct',
            name='sku',
            field=models.CharField(blank=True, max_length=80, verbose_name='SKU / Référence'),
        ),
        migrations.AlterField(
            model_name='supplyproduct',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='supply.supplier', verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='supplyproduct',
            name='unit_label',
            field=models.CharField(help_text='Ex: caisse 24 bouteilles, carton 40 paquets', max_length=120, verbose_name='Unité de vente'),
        ),
        migrations.AlterField(
            model_name='supplyproduct',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix de gros'),
        ),
    ]
