# Generated by Django 6.0 on 2025-12-11 16:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'achat")),
                ('supplier', models.CharField(help_text='Nom du fournisseur', max_length=200, verbose_name='Fournisseur')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de facture')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_received', models.BooleanField(default=False, help_text='Cocher quand la marchandise est réceptionnée', verbose_name='Marchandise reçue')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Achat',
                'verbose_name_plural': 'Achats',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text="Prix d'achat au moment de la commande", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="Prix d'achat unitaire")),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Sous-total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='products.product', verbose_name='Produit')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchase', verbose_name='Achat')),
            ],
            options={
                'verbose_name': "Ligne d'achat",
                'verbose_name_plural': "Lignes d'achat",
            },
        ),
    ]
