# Generated by Django 6.0 on 2026-04-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchase_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m', verbose_name='Fichier facture'),
        ),
    ]
