# Generated by Django 6.0 on 2026-01-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_shop_userprofile_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='shop',
            name='bureau',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bureau'),
        ),
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='shop',
            name='id_nat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID.NAT'),
        ),
        migrations.AddField(
            model_name='shop',
            name='nif',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NIF'),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='shop',
            name='rccm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RCCM'),
        ),
        migrations.AddField(
            model_name='shop',
            name='usd_to_cdf_rate',
            field=models.DecimalField(decimal_places=2, default=2800.0, max_digits=10, verbose_name='Taux USD vers CDF'),
        ),
        migrations.AddField(
            model_name='shop',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='Pourcentage TVA (%)'),
        ),
    ]
