# Generated by Django 6.0 on 2026-01-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_shop_address_shop_bureau_shop_email_shop_id_nat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='usd_to_cdf_rate',
            field=models.DecimalField(decimal_places=2, default=2800.0, max_digits=10, verbose_name='Taux de conversion FC'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('FC', 'Franc Congolais (FC)')], default='FC', max_length=3),
        ),
    ]
