# Generated by Django 6.0 on 2026-04-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_update_labels_for_otp_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150, verbose_name="Nom du contact d'urgence"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name="Telephone du contact d'urgence"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Matricule'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes internes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Poste'),
        ),
    ]
