# Generated by Codex on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/', verbose_name='Logo de la boutique'),
        ),
    ]
