# Generated by Django 6.0 on 2025-12-11 16:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('sku', models.CharField(help_text='Code unique du produit (ex: PROD-001)', max_length=50, unique=True, verbose_name='Code SKU')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text="Prix d'achat unitaire HT", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="Prix d'achat")),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Prix de vente TTC', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix de vente')),
                ('current_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock actuel')),
                ('minimum_stock', models.IntegerField(default=5, help_text="Seuil d'alerte pour réapprovisionnement", validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock minimum')),
                ('is_active', models.BooleanField(default=True, help_text='Produit disponible à la vente', verbose_name='Actif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image du produit')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['name'],
            },
        ),
    ]
