# Generated by Django 5.0.6 on 2025-12-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Code-barres unique du produit (EAN-13)', max_length=13, null=True, unique=True, verbose_name='Code-barres'),
        ),
    ]
