# Generated by Django 5.0.6 on 2025-12-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_sku_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(help_text='Code-barres unique du produit (EAN-13)', max_length=13, unique=True, verbose_name='Code-barres'),
        ),
    ]
