# Generated by Django 5.0.6 on 2025-12-13 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_shop_userprofile_shop'),
        ('products', '0003_alter_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.shop'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.shop'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom de la catégorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(help_text='Code-barres unique du produit (EAN-13)', max_length=13, verbose_name='Code-barres'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('shop', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('shop', 'barcode')},
        ),
    ]
