# Generated by Django 6.0 on 2025-12-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_shop_product_shop_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Code-barres unique du produit (EAN-13)', max_length=13, verbose_name='Code-barres'),
        ),
    ]
