# Generated by Django 5.0.6 on 2025-12-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_barcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text="Image affichée sur la page d'accueil", null=True, upload_to='categories/', verbose_name='Image de la catégorie'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Cochez pour afficher cette catégorie dans la section showcase', verbose_name="Afficher sur la page d'accueil"),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Les catégories sont triées par ordre croissant', verbose_name="Ordre d'affichage"),
        ),
    ]
