# Generated by Django 6.0 on 2026-01-04 21:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='secondary_image',
            field=models.ImageField(blank=True, help_text="Image qui s'affiche lorsque la souris passe sur le produit", null=True, upload_to='products/', verbose_name='Image au survol'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, help_text="Prix d'achat unitaire en FC (HT)", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="Prix d'achat"),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, help_text='Prix de vente en FC (TTC)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix de vente'),
        ),
    ]
