# Generated by Django 6.0 on 2026-01-05 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_secondary_image_alter_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du modèle')),
                ('description', models.TextField(blank=True, verbose_name='Description interne')),
                ('rules', models.JSONField(default=dict, help_text='Structure JSON définissant les zones, contraintes et prix.', verbose_name='Règles (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modèle de Personnalisation',
                'verbose_name_plural': 'Modèles de Personnalisation',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='customization_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Si rempli, surcharge les règles du modèle sélectionné. Laissez vide pour utiliser le modèle.', null=True, verbose_name='Règles spécifiques (Surcharge)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_customizable',
            field=models.BooleanField(default=False, help_text="Active le bouton 'Personnaliser' sur la boutique", verbose_name='Produit personnalisable'),
        ),
        migrations.AddField(
            model_name='product',
            name='customization_template',
            field=models.ForeignKey(blank=True, help_text='Sélectionnez un modèle existant pour appliquer ses règles', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.customizationtemplate', verbose_name='Modèle de personnalisation'),
        ),
    ]
