# Generated by Django 6.0 on 2026-01-05 17:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_customizationtemplate_product_customization_rules_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customizationtemplate',
            options={'ordering': ['name'], 'verbose_name': 'Modèle de Personnalisation', 'verbose_name_plural': 'Modèles de Personnalisation'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='customization_rules',
        ),
        migrations.AddField(
            model_name='customizationtemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='product',
            name='customization_rules_override',
            field=models.JSONField(blank=True, default=dict, help_text='Si rempli, ignore le template et utilise ces règles', null=True, verbose_name='Règles spécifiques (Surcharge)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_refundable',
            field=models.BooleanField(default=True, help_text='Décocher pour les produits personnalisés non repris', verbose_name='Produit remboursable'),
        ),
        migrations.AddField(
            model_name='product',
            name='mockup_image',
            field=models.ImageField(blank=True, help_text='Image de base pour la prévisualisation de personnalisation', null=True, upload_to='products/mockups/', verbose_name='Image Mockup (pour preview)'),
        ),
        migrations.AddField(
            model_name='product',
            name='production_delay_days',
            field=models.PositiveIntegerField(default=0, help_text='Jours additionnels pour fabriquer ce produit personnalisé', verbose_name='Délai de production (jours)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='customizationtemplate',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='customizationtemplate',
            name='rules',
            field=models.JSONField(default=dict, help_text='\n        Structure:\n        {\n          "version": "2.0",\n          "zones": [\n            {\n              "id": "text_zone",\n              "type": "text|selection|image|shape",\n              "label": "Gravure",\n              "required": true,\n              "conditions": {"autre_zone": "valeur"},\n              "constraints": {\n                "max_length": 20,\n                "allowed_chars": "regex",\n                "allowed_fonts": ["Arial", "Cursive"]\n              },\n              "price_formula": {\n                "base": 5.00,\n                "per_char": 0.50\n              },\n              "preview_config": {\n                "position": {"x": 50, "y": 50},\n                "size": 20,\n                "color": "#000000"\n              }\n            }\n          ],\n          "special_rules": {\n            "non_refundable": true,\n            "production_delay_days": 3,\n            "legal_notice": "Produit personnalisé non repris"\n          }\n        }\n        ', verbose_name='Règles JSON'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=13, verbose_name='Code-barres'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='customization_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.customizationtemplate', verbose_name='Modèle de personnalisation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_customizable',
            field=models.BooleanField(default=False, help_text='Active la personnalisation sur la boutique', verbose_name='Produit personnalisable'),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_stock',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock minimum'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="Prix d'achat"),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image au survol'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix de vente'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='CustomizationPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customization_data', models.JSONField(verbose_name='Données de personnalisation')),
                ('preview_image', models.ImageField(upload_to='previews/', verbose_name='Image de prévisualisation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Prévisualisation',
                'verbose_name_plural': 'Prévisualisations',
            },
        ),
    ]
