# Generated by Django 6.0 on 2026-01-10 16:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_customizationtemplate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizableComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du composant')),
                ('component_type', models.CharField(choices=[('medallion', 'Médaillon'), ('charm', 'Breloque'), ('bead', 'Perle')], default='medallion', max_length=20)),
                ('image', models.ImageField(upload_to='customization/components/', verbose_name='Image du composant')),
                ('shape_identifier', models.CharField(blank=True, help_text="Identifiant pour le JS (ex: 'heart', 'star', 'round')", max_length=50)),
                ('base_price_modifier', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Surcoût de base')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Composant de Personnalisation',
                'verbose_name_plural': 'Composants de Personnalisation',
            },
        ),
        migrations.CreateModel(
            name='CustomizationFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom de la police')),
                ('font_family', models.CharField(max_length=100, verbose_name="Famille CSS (ex: 'Dancing Script', cursive)")),
                ('font_url', models.URLField(blank=True, verbose_name='URL Google Fonts (optionnel)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Police de Gravure',
                'verbose_name_plural': 'Polices de Gravure',
            },
        ),
        migrations.CreateModel(
            name='ProductCustomizationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_config', models.JSONField(blank=True, default=dict, verbose_name='Configuration Atelier (JSON)')),
                ('allowed_components', models.ManyToManyField(blank=True, to='products.customizablecomponent', verbose_name='Composants autorisés')),
                ('allowed_fonts', models.ManyToManyField(blank=True, to='products.customizationfont', verbose_name='Polices autorisées')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customization_config', to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Configuration Atelier',
                'verbose_name_plural': 'Configurations Atelier',
            },
        ),
    ]
