# Generated by Codex on 2026-02-05
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_color_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='engraving_mode',
            field=models.CharField(choices=[('text', 'Texte uniquement'), ('image', 'Image / Photo uniquement'), ('both', 'Texte + Image')], default='text', max_length=10, verbose_name='Type de gravure'),
        ),
    ]
