# Generated by Django 6.0 on 2026-02-05 20:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_engraving_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='engraving_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prix de gravure'),
        ),
        migrations.AlterField(
            model_name='customizablecomponent',
            name='shape_identifier',
            field=models.CharField(blank=True, help_text="Identifiant pour le JS (ex: 'heart', 'star', 'round', 'dogtag', 'africa', 'cross', 'bar_active')", max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='custom_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur personnalis??e'),
        ),
    ]
